
name: Node.js CI
env:
  BROWSER: "chrome"
  DEVICE: "mobile"
  

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Make script executable
      run: chmod +x test_data_exec.sh

    - name: Fetch Test Data
      env:
        MEGA_EMAIL: ${{ secrets.MEGA_SERVER_EMAIL }}
        MEGA_PASSWORD: ${{ secrets.MEGA_SERVER_PASSWORD }}
        SERVER: "GITHUB"
      run: ./test_data_exec.sh

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
    
    - name: Verify Cypress installation
      run: npx cypress verify

    - name: Run Cypress tests
      run: npm run cy:run -- --browser $BROWSER --env device=$DEVICE

    - name: Upload Cypress HTML Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-html-report
        path: cypress/reports/html/**
